fix

diff --git a/.github/workflows/kernel.yml b/.github/workflows/kernel.yml
--- a/.github/workflows/kernel.yml
+++ b/.github/workflows/kernel.yml
@@ -148,6 +148,38 @@ jobs:
           fi
           # tree kernel_dir
 
+      - name: 😋 Apply kernel patches for the first time
+        if: ${{ env.ENABLE_KERNELSU == 'true' }}
+        run: |
+          # Define the directory containing the patches
+          PATCHES_DIR="$GITHUB_WORKSPACE/kernel_workspace/kernel_dir"
+
+          # Check if the patches directory exists and is not empty
+          if [ -d "$PATCHES_DIR" ] && [ "$(ls -A $PATCHES_DIR)" ]; then
+            echo "🔍 Found patches in $PATCHES_DIR. Applying them now..."
+
+            # Change to the kernel source directory
+            cd $GITHUB_WORKSPACE/kernel_workspace/kernel_dir
+            git apply dsp-hook.patch
+
+            # # Apply each patch
+            # for patch in $PATCHES_DIR/*.patch; do
+            #   echo "📝 Applying $patch"
+            #   # git apply $patch
+              
+
+            #   # Check if the patch was applied successfully
+            #   if [ $? -ne 0 ]; then
+            #     echo "❌ Failed to apply $patch"
+            #     exit 1
+            #   fi
+            # done
+
+            echo "✅ All patches applied successfully"
+          else
+            echo "⚠️ No patches found in $PATCHES_DIR"
+          fi
+
       # Initialize ccache
       - name: 🚄 Setup ccache
         if: ${{ env.ENABLE_CCACHE == 'true' }}
@@ -298,39 +330,6 @@ jobs:
 
           echo "🤔 $args"
 
-      
-      - name: 😋 Apply kernel patches
-        if: ${{ env.ENABLE_KERNELSU == 'true' }}
-        run: |
-          # Define the directory containing the patches
-          PATCHES_DIR="$GITHUB_WORKSPACE/kernel_workspace/kernel_dir"
-          ls
-          # Check if the patches directory exists and is not empty
-          if [ -d "$PATCHES_DIR" ] && [ "$(ls -A $PATCHES_DIR)" ]; then
-            echo "🔍 Found patches in $PATCHES_DIR. Applying them now..."
-
-            # Change to the kernel source directory
-            cd $GITHUB_WORKSPACE/kernel_workspace/kernel_dir
-            git apply KernelSU-hook.patch
-            git apply dsp-hook.patch
-            # # Apply each patch
-            # for patch in $PATCHES_DIR/*.patch; do
-            #   echo "📝 Applying $patch"
-            #   # git apply $patch
-              
-
-            #   # Check if the patch was applied successfully
-            #   if [ $? -ne 0 ]; then
-            #     echo "❌ Failed to apply $patch"
-            #     exit 1
-            #   fi
-            # done
-
-            echo "✅ All patches applied successfully"
-          else
-            echo "⚠️ No patches found in $PATCHES_DIR"
-          fi
-
       - name: 😋 Setup KernelSU
         env:
           ARCH: ${{ steps.generate-args.outputs.ARCH }}
@@ -351,39 +350,34 @@ jobs:
             curl -LSs "${{ env.KERNELSU_INSTALLER }}" | bash -s ${{ env.KERNELSU_TAG }}
           fi
 
-          # if grep -q "CONFIG_KSU" arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}; then
-          #   sed -i 's/# CONFIG_KSU is not set/CONFIG_KSU=y/g' arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
-          #   sed -i 's/CONFIG_KSU=n/CONFIG_KSU=y/g' arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
-          # else
-          #     echo "CONFIG_KSU=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
-          # fi
+          if grep -q "CONFIG_KSU" arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}; then
+            sed -i 's/# CONFIG_KSU is not set/CONFIG_KSU=y/g' arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
+            sed -i 's/CONFIG_KSU=n/CONFIG_KSU=y/g' arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
+          else
+              echo "CONFIG_KSU=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
+          fi
 
-          # Apply KernelSU
-          # if [ ${{ env.APPLY_KSU_PATCH }} = true ]; then
-          #     bash $GITHUB_WORKSPACE/patches/patches.sh
-          # fi
+          if [ ${{ env.ENABLE_KP }} = true -a ${{ env.APPLY_KSU_PATCH }} != true ]; then
+              echo "CONFIG_MODULES=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
+              echo "CONFIG_KPROBES=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
+              echo "CONFIG_HAVE_KPROBES=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
+              echo "CONFIG_KPROBE_EVENTS=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
+          fi
 
-          # if [ ${{ env.ENABLE_KP }} = true -a ${{ env.APPLY_KSU_PATCH }} != true ]; then
-          #     echo "CONFIG_MODULES=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
-          #     echo "CONFIG_KPROBES=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
-          #     echo "CONFIG_HAVE_KPROBES=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
-          #     echo "CONFIG_KPROBE_EVENTS=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
-          # fi
+          if [ ${{ env.ENABLE_OFS }} = true ]; then
+              echo "CONFIG_OVERLAY_FS=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
+          fi
 
-          # if [ ${{ env.ENABLE_OFS }} = true ]; then
-          #     echo "CONFIG_OVERLAY_FS=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
-          # fi
+          if [ ${{ env.DISABLE_LTO }} = true ]; then
+              sed -i 's/CONFIG_LTO=y/CONFIG_LTO=n/' arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
+              sed -i 's/CONFIG_LTO_CLANG=y/CONFIG_LTO_CLANG=n/' arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
+              sed -i 's/CONFIG_THINLTO=y/CONFIG_THINLTO=n/' arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATHKERNEL_DEFCONFIG_PATH }}
+              echo "CONFIG_LTO_NONE=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
+          fi
 
-          # if [ ${{ env.DISABLE_LTO }} = true ]; then
-          #     sed -i 's/CONFIG_LTO=y/CONFIG_LTO=n/' arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
-          #     sed -i 's/CONFIG_LTO_CLANG=y/CONFIG_LTO_CLANG=n/' arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
-          #     sed -i 's/CONFIG_THINLTO=y/CONFIG_THINLTO=n/' arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATHKERNEL_DEFCONFIG_PATH }}
-          #     echo "CONFIG_LTO_NONE=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
-          # fi
-
-          # if [ ${{ env.DISABLE_CC_WERROR }} = true ]; then
-          #     echo "CONFIG_CC_WERROR=n" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
-          # fi
+          if [ ${{ env.DISABLE_CC_WERROR }} = true ]; then
+              echo "CONFIG_CC_WERROR=n" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_DEFCONFIG_PATH }}
+          fi
   
       - name: 😋 Setup LXC docker
         env:
@@ -426,6 +420,38 @@ jobs:
           if [ -f android-kernel/net/netfilter/xt_qtaguid.c ]; then
             git am -s < ${{ env.WORKSPACE }}/LXC/Patches/xt_qtaguid.patch
             echo "🎖️ Apply xt_qtaguid.patch"
+          fi
+
+      - name: 😋 Apply kernel patches for the second time
+        if: ${{ env.ENABLE_KERNELSU == 'true' }}
+        run: |
+          # Define the directory containing the patches
+          PATCHES_DIR="$GITHUB_WORKSPACE/kernel_workspace/kernel_dir"
+
+          # Check if the patches directory exists and is not empty
+          if [ -d "$PATCHES_DIR" ] && [ "$(ls -A $PATCHES_DIR)" ]; then
+            echo "🔍 Found patches in $PATCHES_DIR. Applying them now..."
+
+            # Change to the kernel source directory
+            cd $GITHUB_WORKSPACE/kernel_workspace/kernel_dir
+            git apply KernelSU-hook.patch
+
+            # # Apply each patch
+            # for patch in $PATCHES_DIR/*.patch; do
+            #   echo "📝 Applying $patch"
+            #   # git apply $patch
+              
+
+            #   # Check if the patch was applied successfully
+            #   if [ $? -ne 0 ]; then
+            #     echo "❌ Failed to apply $patch"
+            #     exit 1
+            #   fi
+            # done
+
+            echo "✅ All patches applied successfully"
+          else
+            echo "⚠️ No patches found in $PATCHES_DIR"
           fi
 
       - name: 👍 Start building the kernel
